/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_sgbd;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Ibrah
 */
public class main_menu extends javax.swing.JFrame {
    
    Connection connection;
    /**
     * Creates new form main_menu
     */
    public main_menu() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        getRootPane().setBorder(BorderFactory.createMatteBorder(3, 1, 1, 1, java.awt.SystemColor.textHighlight));
        combo_databases.setBackground(Color.gray);
       
        
        button_exit.setBorder(null);
        button_exit.setBorderPainted(false);
        button_exit.setContentAreaFilled(false);
        button_minimize.setBorder(null);
        button_minimize.setBorderPainted(false);
        button_minimize.setContentAreaFilled(false);
        
        /*------------------------Panels----------------------------------*/
        
        /*Connexion*/
        panel_connexion.setVisible(false);
        panel_connexion.setBackground(Color.WHITE);
        
        /*-----------------------Text boxes-----------------------------*/
        
        /*User*/
        textbox_user.setForeground(Color.LIGHT_GRAY);
        textbox_user.setText("Nom d'utilisateur...");
        textbox_user.setFont(new java.awt.Font("Segoe UI Light", 2, 12));
        
        /*Password*/
        textbox_password.setForeground(Color.lightGray);
        textbox_password.setText("Mot de passe...");
        textbox_password.setFont(new java.awt.Font("Segoe UI Light", 2, 12));
    }
    
    public void connexionMySQL(String login, String password) {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println(password);
            connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT&user="+login+"&password="+password);
            JOptionPane.showMessageDialog(rootPane, "Connexion réussie!");
            JFrame home = new home(connection,"MySQL");
            home.setVisible(rootPaneCheckingEnabled);
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Erreur lors de la connexion! Message d'erreur: " +e.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erreur lors du chargement du driver. Message d'erreur: " + ex.getMessage());
        }
    }
    
    public void connexionDerby(){
        try{
            
        }catch(Exception e){
            
        }
    }
    
    public void connexionPostgre(){
        try{
            
        }catch(Exception e){
            
        }
    }
    
    public void connexionOracle(){
        try{
            
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_connexion = new javax.swing.JPanel();
        label_connexion = new javax.swing.JLabel();
        textbox_user = new javax.swing.JTextField();
        button_connexion = new javax.swing.JButton();
        textbox_password = new javax.swing.JPasswordField();
        label_identification = new javax.swing.JLabel();
        combo_databases = new javax.swing.JComboBox<>();
        button_exit = new javax.swing.JButton();
        button_minimize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setIconImages(null);
        setLocation(new java.awt.Point(500, 100));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("frame"); // NOI18N
        setUndecorated(true);

        label_connexion.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        label_connexion.setForeground(new java.awt.Color(153, 153, 153));
        label_connexion.setText("Connexion");

        textbox_user.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textbox_user.setToolTipText("");
        textbox_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textbox_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textbox_userFocusLost(evt);
            }
        });
        textbox_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_userActionPerformed(evt);
            }
        });

        button_connexion.setBackground(java.awt.SystemColor.textHighlight);
        button_connexion.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        button_connexion.setForeground(new java.awt.Color(255, 255, 255));
        button_connexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Connect_30px.png"))); // NOI18N
        button_connexion.setText("Se connecter");
        button_connexion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_connexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_connexionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_connexionMouseExited(evt);
            }
        });
        button_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_connexionActionPerformed(evt);
            }
        });

        textbox_password.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textbox_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textbox_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textbox_passwordFocusLost(evt);
            }
        });
        textbox_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textbox_passwordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_connexionLayout = new javax.swing.GroupLayout(panel_connexion);
        panel_connexion.setLayout(panel_connexionLayout);
        panel_connexionLayout.setHorizontalGroup(
            panel_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_connexionLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panel_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_connexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_connexionLayout.createSequentialGroup()
                        .addGroup(panel_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textbox_password, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_connexionLayout.createSequentialGroup()
                                    .addGap(97, 97, 97)
                                    .addComponent(label_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_connexionLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(textbox_user, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        panel_connexionLayout.setVerticalGroup(
            panel_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_connexionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label_connexion)
                .addGap(18, 18, 18)
                .addComponent(textbox_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(textbox_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(button_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        label_identification.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        label_identification.setForeground(java.awt.SystemColor.textHighlight);
        label_identification.setText("Identification");

        combo_databases.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        combo_databases.setForeground(new java.awt.Color(255, 255, 255));
        combo_databases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionnez un SGBD...", "PostgreSQL", "MySQL", "OracleDB", "Derby" }));
        combo_databases.setBorder(null);
        combo_databases.setFocusable(false);
        combo_databases.setLightWeightPopupEnabled(false);
        combo_databases.setRequestFocusEnabled(false);
        combo_databases.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_databasesItemStateChanged(evt);
            }
        });

        button_exit.setBackground(new java.awt.Color(255, 255, 255));
        button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Close Window_30px.png"))); // NOI18N
        button_exit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button_exit.setBorderPainted(false);
        button_exit.setFocusPainted(false);
        button_exit.setFocusable(false);
        button_exit.setRequestFocusEnabled(false);
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        button_minimize.setBackground(new java.awt.Color(255, 255, 255));
        button_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Reduce_30px.png"))); // NOI18N
        button_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_minimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(combo_databases, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_identification)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                        .addComponent(button_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_exit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_exit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_minimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_identification)))
                .addGap(75, 75, 75)
                .addComponent(combo_databases, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("JFrame\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_databasesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_databasesItemStateChanged
        // TODO add your handling code here:*
        int index = combo_databases.getSelectedIndex();
        
        if(panel_connexion.isVisible() == false && index !=0){
        panel_connexion.setVisible(true);
        }
        else if(index == 0){
            panel_connexion.setVisible(false);
        }
    }//GEN-LAST:event_combo_databasesItemStateChanged

    private void changeUserTextboxStyle(){
    
        if(textbox_user.getFont().equals(new java.awt.Font("Segoe UI Light", 2, 12))){
            textbox_user.setForeground(Color.black);
            textbox_user.setText("");
            textbox_user.setFont(new java.awt.Font("Segoe UI Light", 0, 12));   
        }
        else if(textbox_user.getText().equals("")){
            textbox_user.setText("Nom d'utilisateur...");
            textbox_user.setFont(new java.awt.Font("Segoe UI Light", 2, 12));
            textbox_user.setForeground(Color.LIGHT_GRAY);
        }
    }
    
    private void changePasswordTextBoxStyle(){
        
        if(textbox_password.getFont().equals(new java.awt.Font("Segoe UI Light", 2, 12))){
            textbox_password.setForeground(Color.black);
            textbox_password.setText("");
            textbox_password.setFont(new java.awt.Font("Segoe UI Light", 0, 12));   
        }
        else if(textbox_password.getText().equals("")){
            textbox_password.setText("Mot de passe...");
            textbox_password.setFont(new java.awt.Font("Segoe UI Light", 2, 12));
            textbox_password.setForeground(Color.LIGHT_GRAY);
        }      
    }
    
    
    private void textbox_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbox_userFocusGained
        // TODO add your handling code here:
        changeUserTextboxStyle();
    }//GEN-LAST:event_textbox_userFocusGained

    private void textbox_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbox_userFocusLost
        // TODO add your handling code here:
         changeUserTextboxStyle();
    }//GEN-LAST:event_textbox_userFocusLost

    private void textbox_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_userActionPerformed
        // TODO add your handling code here:
        changeUserTextboxStyle();
    }//GEN-LAST:event_textbox_userActionPerformed

    private void button_connexionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_connexionMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_button_connexionMouseEntered

    private void button_connexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_connexionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button_connexionMouseExited

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Voulez-vous vraiment quitter ?");
        if(choice == 0){
            dispose();
        }
    }//GEN-LAST:event_button_exitActionPerformed

    private void button_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_minimizeActionPerformed
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_button_minimizeActionPerformed

    private void button_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_connexionActionPerformed
        // TODO add your handling code here:
        if(combo_databases.getSelectedIndex()==2){
            connexionMySQL(textbox_user.getText(), new String(textbox_password.getPassword()));
        }
    }//GEN-LAST:event_button_connexionActionPerformed

    private void textbox_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbox_passwordFocusGained
        // TODO add your handling code here:
        changePasswordTextBoxStyle();
    }//GEN-LAST:event_textbox_passwordFocusGained

    private void textbox_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textbox_passwordFocusLost
        // TODO add your handling code here:
        changePasswordTextBoxStyle();
    }//GEN-LAST:event_textbox_passwordFocusLost

    private void textbox_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textbox_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            if(combo_databases.getSelectedIndex() == 2){
                connexionMySQL(textbox_user.getText(), new String(textbox_password.getPassword()));
            }
        }
    }//GEN-LAST:event_textbox_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new main_menu().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_connexion;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_minimize;
    private static javax.swing.JComboBox<String> combo_databases;
    private javax.swing.JLabel label_connexion;
    private javax.swing.JLabel label_identification;
    private static javax.swing.JPanel panel_connexion;
    private javax.swing.JPasswordField textbox_password;
    private javax.swing.JTextField textbox_user;
    // End of variables declaration//GEN-END:variables
}
